apps/books/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index,name='index')
]

apps/log_reg/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index,name='index'),
	url(r'^success$', views.success,name='success'),
	url(r'^logout$', views.logout,name='logout')
]

belt_review/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books', include('apps.books.urls', namespace="books")),
    url(r'^', include('apps.log_reg.urls', namespace="authenticate"))
]

apps/books/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/log_reg/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib import messages
from django.shortcuts import render, redirect
import bcrypt
import re

class UserManager(models.Manager):
	def reg_check(self, postData):

		EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
		# checks for a valid email format: email@email.com

		name_match = r'^[a-zA-Z]+$'	
		# accepts only alpha characters in a name

		pass_require = r'(?=.*[A-Z]+)(?=.*[0-9]+)'
		# password requires at least one upper case letter and one number

		error_messages = []

		if len(postData['first']) < 2:
			error_messages.append('First name must contain at least 2 characters!')
			
		if not re.search(name_match, postData['first']):
			error_messages.append('First name must have only letters!')
			
		if len(postData['last']) < 2:
			error_messages.append('Last name must contain at least 2 characters!')
			
		if not re.search(name_match, postData['last']):
			error_messages.append('Last name must have only letters!')
				
		if not postData['email']:
			error_messages.append('Email address is required!')
			
		if not EMAIL_REGEX.match(postData['email']):
			error_messages.append('Email address needs to be in a valid format!')

		else:
			email_check = self.filter(email=postData['email'])
			if email_check:
				error_messages.append('Email address is already in the database!')	
			
		if not postData['password']:
			error_messages.append("Password cannot be blank! Password must be at least 8 characters and contain at least 1 capital letter and 1 number!")
		
		else:	
			if len(postData['password']) < 8:
				error_messages.append("Password cannot be less than 8 characters!")
				
			if not re.search(pass_require, postData['password']):
				error_messages.append("Password must contain at least 1 capital letter and 1 number!")
				
		if postData['confirm_password'] != postData['password']:
			error_messages.append("Confirm password and password must match!")
					
		response = {}				

		if error_messages:
			response['errors'] = error_messages
			response['created'] = False

		else:
			pw_hash = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
			new_user = self.create(email=postData['email'],first_name=postData['first'],last_name=postData['last'],pw_hash=pw_hash)
			response['created'] = True
			response['new_user'] = new_user

		return response

	def login_check(self, postData):

		error_messages = []
		email_check = User.objects.filter(email=postData['email'])
		response = {}

		if not email_check:
			error_messages.append("Email does not exist in system! Please register!")
			response['login'] = False
		else:
			if bcrypt.hashpw(postData['password'].encode(), email_check[0].pw_hash.encode()) == email_check[0].pw_hash:
				response['login'] = True
				response['user'] = email_check[0]
			else:	
				error_messages.append("Password is invalid!")
				response['login'] = False

		response['errors'] = error_messages

		return response	
						
class User(models.Model):
	first_name=models.CharField(max_length=100)
	last_name=models.CharField(max_length=100)
	email=models.CharField(max_length=100)
	pw_hash=models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add = True)
	objects = UserManager()

apps/books/views.py
from django.shortcuts import render, redirect

def index(request):
	return render(request, 'books/index.html')

apps/log_reg/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import User

def index(request):
	if request.method=="GET":
		return render(request, 'log_reg/index.html')

	if request.method=="POST":
		if request.POST['process'] == 'registration':
			check = User.objects.reg_check(request.POST)
			if check['created']:
				request.session['user'] = {
			        'id' : check['new_user'].id,
			        'first_name' : check['new_user'].first_name,
			        'last_name' : check['new_user'].last_name,
			        'email' : check['new_user'].email,
			    }
				messages.success(request, "Success! Welcome {}!".format(request.session['user']['first_name']))
				return redirect(reverse('authenticate:success'))	
			else:
				for x in check['errors']:
					messages.error(request, x)
				return redirect(reverse('authenticate:index'))
		
		elif request.POST['process'] == 'login':
			check = User.objects.login_check(request.POST)
			if check['login'] == True:
				request.session['user'] = {
			        'id' : check['user'].id,
			        'first_name' : check['user'].first_name,
			        'last_name' : check['user'].last_name,
			        'email' : check['user'].email,
			    }
				messages.success(request, "Hi {}! You successfully logged in!".format(request.session['user']['first_name']))
				return redirect(reverse('authenticate:success'))
			else:
				for x in check['errors']:
					messages.error(request, x)
				return redirect(reverse('authenticate:index'))		

def logout(request):
	if request.method=="GET":
		del request.session['user']
		messages.success(request, 'Success! You were logged out!')
		return redirect(reverse('authenticate:index'))				

def success(request):
	if request.method=="GET":
		if not 'user' in request.session:
			messages.error(request, "Sorry you are not logged in!")
			return redirect(reverse('authenticate:index'))
		else:	
			return render(request, 'log_reg/success.html')		

apps/books/templates/books/index.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
Hello World!
</body>
</html>

apps/log_reg/templates/log_reg/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset='utf-8'>
	<title>User Reg</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	</link>
</head>
<body>
	{% if messages %}
    	{% for message in messages %}
    		<p>{{ message }}</p>
    	{% endfor %}
	{% endif %}
	<h1>Registration</h1>
	<form action='{% url "authenticate:index" %}' method='POST'>
		{% csrf_token %}
		<input type="hidden" name="process" value="registration">
		First Name: <input type="text" name="first"/>
		Last Name: <input type="text" name="last"/>
		Email: <input type="text" name="email"/>
		Password: <input type="text" name="password"/>
		Password Confirm: <input type="text" name="confirm_password"/>
		<input type="submit" value="Submit" />
	</form>
	<form action='{% url "authenticate:index" %}' method='POST'>
		{% csrf_token %}
		<input type="hidden" name="process" value="login">
		Email: <input type="text" name="email"/>
		Password: <input type="text" name="password"/>
		<input type="submit" value="Submit" />
	</form>
</body>
</html>

apps/log_reg/templates/log_reg/success.html
<!DOCTYPE html>
<html>
<head>
	<title>Email Validation</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	</link>
</head>
<body>
	{% if messages %}
    	{% for message in messages %}
    		<h1>{{ message }}</h1>
    	{% endfor %}
	{% endif %}
	<h2>Successfully registered (or logged in)!</h2>
	<a href='{% url "authenticate:logout" %}'>Logout</a>
</body>
</html>